version: '3'

services:
  database:
    container_name: mysql
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: Insta
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: tjdgns112
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - test_network

  application:
    container_name: docker-compose-test
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/Insta
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network: